// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: blockmazechain/validatorbonus/query.proto

package validatorbonus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName               = "/blockmazechain.validatorbonus.Query/Params"
	Query_EligibleValidator_FullMethodName    = "/blockmazechain.validatorbonus.Query/EligibleValidator"
	Query_EligibleValidatorAll_FullMethodName = "/blockmazechain.validatorbonus.Query/EligibleValidatorAll"
	Query_ProposerCount_FullMethodName        = "/blockmazechain.validatorbonus.Query/ProposerCount"
	Query_ProposerCountAll_FullMethodName     = "/blockmazechain.validatorbonus.Query/ProposerCountAll"
	Query_DailyReward_FullMethodName          = "/blockmazechain.validatorbonus.Query/DailyReward"
	Query_DailyRewardAll_FullMethodName       = "/blockmazechain.validatorbonus.Query/DailyRewardAll"
	Query_CycleReward_FullMethodName          = "/blockmazechain.validatorbonus.Query/CycleReward"
	Query_CycleRewardAll_FullMethodName       = "/blockmazechain.validatorbonus.Query/CycleRewardAll"
	Query_ValidatorCycleReward_FullMethodName = "/blockmazechain.validatorbonus.Query/ValidatorCycleReward"
	Query_CycleRewards_FullMethodName         = "/blockmazechain.validatorbonus.Query/CycleRewards"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of EligibleValidator items.
	EligibleValidator(ctx context.Context, in *QueryGetEligibleValidatorRequest, opts ...grpc.CallOption) (*QueryGetEligibleValidatorResponse, error)
	EligibleValidatorAll(ctx context.Context, in *QueryAllEligibleValidatorRequest, opts ...grpc.CallOption) (*QueryAllEligibleValidatorResponse, error)
	// Queries a list of ProposerCount items.
	ProposerCount(ctx context.Context, in *QueryGetProposerCountRequest, opts ...grpc.CallOption) (*QueryGetProposerCountResponse, error)
	ProposerCountAll(ctx context.Context, in *QueryAllProposerCountRequest, opts ...grpc.CallOption) (*QueryAllProposerCountResponse, error)
	// Queries a list of DailyReward items.
	DailyReward(ctx context.Context, in *QueryGetDailyRewardRequest, opts ...grpc.CallOption) (*QueryGetDailyRewardResponse, error)
	DailyRewardAll(ctx context.Context, in *QueryAllDailyRewardRequest, opts ...grpc.CallOption) (*QueryAllDailyRewardResponse, error)
	// Queries a list of CycleReward items.
	CycleReward(ctx context.Context, in *QueryGetCycleRewardRequest, opts ...grpc.CallOption) (*QueryGetCycleRewardResponse, error)
	CycleRewardAll(ctx context.Context, in *QueryAllCycleRewardRequest, opts ...grpc.CallOption) (*QueryAllCycleRewardResponse, error)
	// Queries a list of ValidatorCycleReward items.
	ValidatorCycleReward(ctx context.Context, in *QueryValidatorCycleRewardRequest, opts ...grpc.CallOption) (*QueryValidatorCycleRewardResponse, error)
	// Queries a list of CycleRewards items.
	CycleRewards(ctx context.Context, in *QueryCycleRewardsRequest, opts ...grpc.CallOption) (*QueryCycleRewardsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EligibleValidator(ctx context.Context, in *QueryGetEligibleValidatorRequest, opts ...grpc.CallOption) (*QueryGetEligibleValidatorResponse, error) {
	out := new(QueryGetEligibleValidatorResponse)
	err := c.cc.Invoke(ctx, Query_EligibleValidator_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EligibleValidatorAll(ctx context.Context, in *QueryAllEligibleValidatorRequest, opts ...grpc.CallOption) (*QueryAllEligibleValidatorResponse, error) {
	out := new(QueryAllEligibleValidatorResponse)
	err := c.cc.Invoke(ctx, Query_EligibleValidatorAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProposerCount(ctx context.Context, in *QueryGetProposerCountRequest, opts ...grpc.CallOption) (*QueryGetProposerCountResponse, error) {
	out := new(QueryGetProposerCountResponse)
	err := c.cc.Invoke(ctx, Query_ProposerCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProposerCountAll(ctx context.Context, in *QueryAllProposerCountRequest, opts ...grpc.CallOption) (*QueryAllProposerCountResponse, error) {
	out := new(QueryAllProposerCountResponse)
	err := c.cc.Invoke(ctx, Query_ProposerCountAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DailyReward(ctx context.Context, in *QueryGetDailyRewardRequest, opts ...grpc.CallOption) (*QueryGetDailyRewardResponse, error) {
	out := new(QueryGetDailyRewardResponse)
	err := c.cc.Invoke(ctx, Query_DailyReward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DailyRewardAll(ctx context.Context, in *QueryAllDailyRewardRequest, opts ...grpc.CallOption) (*QueryAllDailyRewardResponse, error) {
	out := new(QueryAllDailyRewardResponse)
	err := c.cc.Invoke(ctx, Query_DailyRewardAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CycleReward(ctx context.Context, in *QueryGetCycleRewardRequest, opts ...grpc.CallOption) (*QueryGetCycleRewardResponse, error) {
	out := new(QueryGetCycleRewardResponse)
	err := c.cc.Invoke(ctx, Query_CycleReward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CycleRewardAll(ctx context.Context, in *QueryAllCycleRewardRequest, opts ...grpc.CallOption) (*QueryAllCycleRewardResponse, error) {
	out := new(QueryAllCycleRewardResponse)
	err := c.cc.Invoke(ctx, Query_CycleRewardAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorCycleReward(ctx context.Context, in *QueryValidatorCycleRewardRequest, opts ...grpc.CallOption) (*QueryValidatorCycleRewardResponse, error) {
	out := new(QueryValidatorCycleRewardResponse)
	err := c.cc.Invoke(ctx, Query_ValidatorCycleReward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CycleRewards(ctx context.Context, in *QueryCycleRewardsRequest, opts ...grpc.CallOption) (*QueryCycleRewardsResponse, error) {
	out := new(QueryCycleRewardsResponse)
	err := c.cc.Invoke(ctx, Query_CycleRewards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of EligibleValidator items.
	EligibleValidator(context.Context, *QueryGetEligibleValidatorRequest) (*QueryGetEligibleValidatorResponse, error)
	EligibleValidatorAll(context.Context, *QueryAllEligibleValidatorRequest) (*QueryAllEligibleValidatorResponse, error)
	// Queries a list of ProposerCount items.
	ProposerCount(context.Context, *QueryGetProposerCountRequest) (*QueryGetProposerCountResponse, error)
	ProposerCountAll(context.Context, *QueryAllProposerCountRequest) (*QueryAllProposerCountResponse, error)
	// Queries a list of DailyReward items.
	DailyReward(context.Context, *QueryGetDailyRewardRequest) (*QueryGetDailyRewardResponse, error)
	DailyRewardAll(context.Context, *QueryAllDailyRewardRequest) (*QueryAllDailyRewardResponse, error)
	// Queries a list of CycleReward items.
	CycleReward(context.Context, *QueryGetCycleRewardRequest) (*QueryGetCycleRewardResponse, error)
	CycleRewardAll(context.Context, *QueryAllCycleRewardRequest) (*QueryAllCycleRewardResponse, error)
	// Queries a list of ValidatorCycleReward items.
	ValidatorCycleReward(context.Context, *QueryValidatorCycleRewardRequest) (*QueryValidatorCycleRewardResponse, error)
	// Queries a list of CycleRewards items.
	CycleRewards(context.Context, *QueryCycleRewardsRequest) (*QueryCycleRewardsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) EligibleValidator(context.Context, *QueryGetEligibleValidatorRequest) (*QueryGetEligibleValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EligibleValidator not implemented")
}
func (UnimplementedQueryServer) EligibleValidatorAll(context.Context, *QueryAllEligibleValidatorRequest) (*QueryAllEligibleValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EligibleValidatorAll not implemented")
}
func (UnimplementedQueryServer) ProposerCount(context.Context, *QueryGetProposerCountRequest) (*QueryGetProposerCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposerCount not implemented")
}
func (UnimplementedQueryServer) ProposerCountAll(context.Context, *QueryAllProposerCountRequest) (*QueryAllProposerCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposerCountAll not implemented")
}
func (UnimplementedQueryServer) DailyReward(context.Context, *QueryGetDailyRewardRequest) (*QueryGetDailyRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DailyReward not implemented")
}
func (UnimplementedQueryServer) DailyRewardAll(context.Context, *QueryAllDailyRewardRequest) (*QueryAllDailyRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DailyRewardAll not implemented")
}
func (UnimplementedQueryServer) CycleReward(context.Context, *QueryGetCycleRewardRequest) (*QueryGetCycleRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CycleReward not implemented")
}
func (UnimplementedQueryServer) CycleRewardAll(context.Context, *QueryAllCycleRewardRequest) (*QueryAllCycleRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CycleRewardAll not implemented")
}
func (UnimplementedQueryServer) ValidatorCycleReward(context.Context, *QueryValidatorCycleRewardRequest) (*QueryValidatorCycleRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorCycleReward not implemented")
}
func (UnimplementedQueryServer) CycleRewards(context.Context, *QueryCycleRewardsRequest) (*QueryCycleRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CycleRewards not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EligibleValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEligibleValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EligibleValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EligibleValidator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EligibleValidator(ctx, req.(*QueryGetEligibleValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EligibleValidatorAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllEligibleValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EligibleValidatorAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EligibleValidatorAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EligibleValidatorAll(ctx, req.(*QueryAllEligibleValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProposerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProposerCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProposerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ProposerCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProposerCount(ctx, req.(*QueryGetProposerCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProposerCountAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllProposerCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProposerCountAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ProposerCountAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProposerCountAll(ctx, req.(*QueryAllProposerCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DailyReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDailyRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DailyReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DailyReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DailyReward(ctx, req.(*QueryGetDailyRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DailyRewardAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDailyRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DailyRewardAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DailyRewardAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DailyRewardAll(ctx, req.(*QueryAllDailyRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CycleReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCycleRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CycleReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CycleReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CycleReward(ctx, req.(*QueryGetCycleRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CycleRewardAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCycleRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CycleRewardAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CycleRewardAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CycleRewardAll(ctx, req.(*QueryAllCycleRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorCycleReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorCycleRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorCycleReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ValidatorCycleReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorCycleReward(ctx, req.(*QueryValidatorCycleRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CycleRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCycleRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CycleRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CycleRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CycleRewards(ctx, req.(*QueryCycleRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockmazechain.validatorbonus.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "EligibleValidator",
			Handler:    _Query_EligibleValidator_Handler,
		},
		{
			MethodName: "EligibleValidatorAll",
			Handler:    _Query_EligibleValidatorAll_Handler,
		},
		{
			MethodName: "ProposerCount",
			Handler:    _Query_ProposerCount_Handler,
		},
		{
			MethodName: "ProposerCountAll",
			Handler:    _Query_ProposerCountAll_Handler,
		},
		{
			MethodName: "DailyReward",
			Handler:    _Query_DailyReward_Handler,
		},
		{
			MethodName: "DailyRewardAll",
			Handler:    _Query_DailyRewardAll_Handler,
		},
		{
			MethodName: "CycleReward",
			Handler:    _Query_CycleReward_Handler,
		},
		{
			MethodName: "CycleRewardAll",
			Handler:    _Query_CycleRewardAll_Handler,
		},
		{
			MethodName: "ValidatorCycleReward",
			Handler:    _Query_ValidatorCycleReward_Handler,
		},
		{
			MethodName: "CycleRewards",
			Handler:    _Query_CycleRewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockmazechain/validatorbonus/query.proto",
}
